### ISSUE TITLE
关于选中识别改进建议

### ISSUE THREAD

**Issue by Ashinch** [JavaHello/vscode-translate#1]
使用了该扩展已经有一段时间了，总体来说体验很好，有很难受的一点就是：**只有**针对选中代码框中的文字时，按下快捷键才有响应；**在选中VScode自身窗体（例如API提示窗口、插件描述窗口等）中的文字后，按下翻译快捷键并没有产生响应**。

如果能改进这一点，那将是很完美的翻译扩展呢！

**Comment by JavaHello** [comment]
谢谢你的建议，我在尝试加入这个功能时发现，VScode 在选择`自身窗体（例如API提示窗口、插件描述窗口等）`这些窗口的字符时，无法触发指定的`翻译快捷键`，和`右键菜单栏`。这个功能暂时无法加入。
